# -*- coding: utf-8 -*-
"""Pneumonia Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b_5En0Fj_7JWRTivxYkVVPKx9uxxppvL
"""

!pip install streamlit
!pip install tensorflow

import streamlit as st
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image

# Load the saved model
model = load_model('pneumonia_detection_model.h5')

# Title of the app
st.title('Pneumonia Detection')

# File uploader for user to upload an X-ray image
uploaded_file = st.file_uploader("Choose an X-ray image...", type=["jpg", "jpeg", "png"])

if uploaded_file is not None:
    # Load and preprocess the image
    img = image.load_img(uploaded_file, target_size=(150, 150))  # Adjust size as per your model
    img_array = image.img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0) / 255.0  # Normalize the image

    # Button to make prediction
    if st.button('Predict'):
        prediction = model.predict(img_array)
        class_label = 'Pneumonia' if prediction[0][0] > 0.5 else 'Normal'
        st.write(f'Predicted Class: {class_label}')

